### ISSUE TITLE
build:aot throws error

### ISSUE THREAD

**Issue by fxck** [katallaxie/angular2-preboot#47]
haven't changed anything, it's clean install

```
/Users/fxck/www/angular2-preboot/node_modules/@ngtools/webpack/src/refactor.js:14
        throw new Error("Trying to resolve '" + filePath + "' without a basePath.");
              ^
Error: Trying to resolve 'src/main.browser.ts' without a basePath.
    at resolve (/Users/fxck/www/angular2-preboot/node_modules/@ngtools/webpack/src/refactor.js:14:15)
    at new TypeScriptFileRefactor (/Users/fxck/www/angular2-preboot/node_modules/@ngtools/webpack/src/refactor.js:23:20)
    at Object.resolveEntryModuleFromMain (/Users/fxck/www/angular2-preboot/node_modules/@ngtools/webpack/src/entry_resolver.js:108:18)
    at AotPlugin._setupOptions (/Users/fxck/www/angular2-preboot/node_modules/@ngtools/webpack/src/plugin.js:158:54)
    at new AotPlugin (/Users/fxck/www/angular2-preboot/node_modules/@ngtools/webpack/src/plugin.js:17:14)
    at prodConfig (/Users/fxck/www/angular2-preboot/webpack.config.ts:388:25)
    at Object.<anonymous> (/Users/fxck/www/angular2-preboot/webpack.config.ts:415:72)
    at Module._compile (module.js:556:32)
    at Module.m._compile (/Users/fxck/www/angular2-preboot/node_modules/ts-node/src/index.ts:406:23)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/fxck/www/angular2-preboot/node_modules/ts-node/src/index.ts:409:12)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at requireConfig (/Users/fxck/www/angular2-preboot/node_modules/webpack/bin/convert-argv.js:97:18)
    at /Users/fxck/www/angular2-preboot/node_modules/webpack/bin/convert-argv.js:110:17
    at Array.forEach (native)
    at module.exports (/Users/fxck/www/angular2-preboot/node_modules/webpack/bin/convert-argv.js:108:15)
    at Object.<anonymous> (/Users/fxck/www/angular2-preboot/node_modules/webpack/bin/webpack.js:152:40)
    at Module._compile (module.js:556:32)

```

**Comment by fxck** [comment]
I think it can be solved with `root()` helper here https://github.com/katallaxie/angular2-preboot/blob/master/webpack.config.ts#L390 but it then throws another error

```
/Users/fxck/www/conpost-build/application/node_modules/@ngtools/webpack/src/plugin.js:210
        compiler.resolvers.normal.plugin('resolve', function (request, cb) {
                                 ^
TypeError: Cannot read property 'plugin' of null
    at AotPlugin.apply (/Users/fxck/www/conpost-build/application/node_modules/@ngtools/webpack/src/plugin.js:210:34)
    at Compiler.apply (/Users/fxck/www/conpost-build/application/node_modules/tapable/lib/Tapable.js:270:16)
    at webpack (/Users/fxck/www/conpost-build/application/node_modules/webpack/lib/webpack.js:32:19)
    at processOptions (/Users/fxck/www/conpost-build/application/node_modules/webpack/bin/webpack.js:299:14)
    at Object.<anonymous> (/Users/fxck/www/conpost-build/application/node_modules/webpack/bin/webpack.js:359:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by fxck** [comment]
looks like a problem with rc.3 https://github.com/angular/angular-cli/pull/3786 fixed already, not released yet

**Comment by katallaxie** [comment]
ac74ae7c0b8148dcf081f8c8f6be4b73f2a36dca removes `build:aot`, AoT is done by default in `build:prod`. Because I see it as best practice.

**Comment by fxck** [comment]
hm, how does AOT work with `build:prod` exactly @katallaxie ?

```
    config.plugins.push(new AotPlugin({
      tsConfigPath: 'tsconfig.json',
      mainPath: 'src/main.browser.ts',
    }));
```

this never runs when using `build:prod`

**Comment by fxck** [comment]
Maybe I'm either blind or stupid, but I don't see anything other than `AotPlugin` in neither webpack config, nor package.json that would be able to do aot, and I'm pretty sure the `AotPlugin` is never pushed to the config, as I tried replacing the inside of that condition with `throw new Error('boob');` and running `build:prod` and it compiled without throwing.

**Comment by fxck** [comment]
`v1.0.0-beta.25` was released, it should now work with webpack2 rc.3

**Comment by katallaxie** [comment]
@fxck saw that, will update with some other changes.
